# Generated by Django 5.0.2 on 2024-02-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regi',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='regi',
            name='year',
        ),
    ]
