# Generated by Django 5.0.2 on 2024-02-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_remove_regi_branch_remove_regi_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
