# Generated by Django 5.0.2 on 2024-02-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_alter_regi_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regi',
            new_name='student',
        ),
    ]
